projectV2/Models/Applicant.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace GMUAdmissionPortal.Models
{
    public class Applicant
    {
        public int ID { get; set; }

        [Display(Name = "First Name")]
        [Required(ErrorMessage = "Please enter your first name")]
        [StringLength(20, ErrorMessage = "First name can contain only 20 characters")]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "Only characters are allowed")]
        public string FirstName { get; set; }

        [Display(Name = "Middle Name")]
        [StringLength(20, ErrorMessage = "Middle name can contain only 20 characters")]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "Only characters are allowed")]
        public string MiddleName { get; set; }
        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Please enter your last name")]
        [StringLength(20, ErrorMessage = "Last name can contain only 20 characters")]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "Only characters are allowed")]
        public string LastName { get; set; }

        [Display(Name = "SSN")]
        [Required(ErrorMessage = "Please enter your Social Security Number")]
        [MinLength(9, ErrorMessage = "Please enter a valid SSN with 9 numbers")]
        [StringLength(9, ErrorMessage = "Please enter a valid SSN with 9 numbers")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Only numbers are allowed")]
        public string SSN { get; set; }
        [Display(Name = "Email Adress")]
        [Required]
        [DataType(DataType.EmailAddress, ErrorMessage = "Email is not valid")]
        public string EmailAddress { get; set; }
        [Display(Name = "Home Phone")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Only numbers are allowed")]
        public string HomePhone { get; set; }
        [Display(Name = "Cell Phone")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Only numbers are allowed")]
        public string CellPhone { get; set; }

        // Address
        [Display(Name = "Street")]
        public string Street { get; set; }
        [Display(Name = "City")]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "Only characters are allowed")]
        public string City { get; set; }
        [Display(Name = "State")]
        public string State { get; set; }
        [Display(Name = "Zip Code")]
         [Range(10000, 99999, ErrorMessage = "Zipcode must be 5 digits long.")]
        public int Zipcode { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime DOB { get; set; }

        [Display(Name = "Gender")]
        public string Gender { get; set; }

        // High school
        [Display(Name = "Highschool Name")]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "Only characters are allowed")]
        public string HSName { get; set; }
        [Display(Name = "Highschool City")]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "Only characters are allowed")]
        public string HSCity { get; set; }

        // graduation
        [Display(Name = "Graduation Date")]
        [DataType(DataType.Date)]
        public DateTime GraduationDate { get; set; }

        [Display(Name = "Current GPA")]
        [Required]
        [Range(3.0, 4.0, ErrorMessage = "You are not qualified. The minimum GPA for admission is 3.0.")]
        public double GPA { get; set; }

        [Display(Name = "SAT Math Score")]
        [Required]
        [Range(0, 800, ErrorMessage = "Enter a SAT Score between 0-800.")]
        public int MathScore { get; set; }

        [Display(Name = "SAT Verbal Score")]
        [Required]
        [Range(0, 800, ErrorMessage = "Enter a SAT Score between 0-800.")]
        public int VerbalScore { get; set; }

        [Display(Name = "Primary Area of Interest")]
        public string Major { get; set; }

        // enrollment
        [Display(Name = "Enrollment Semester")]
        public string EnrollmentSemester { get; set; }
        [Display(Name = "Enrollment Year")]
        [Range(2020, 2026, ErrorMessage = "Enrollment year should be between 2020 and 2026")]
        public int EnrollmentYear { get; set; }

        [Display(Name = "Admission Decision")]
        public string AdmissionDecision { get; set; }

        [Display(Name = "Submission Date")]
        
        public DateTime SubmissionDate { get; set; }

    }
}

projectV2/Controllers/ApplicantsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GMUAdmissionPortal.Models;
using projectV2.Data;

namespace projectV1.Controllers
{
    public class ApplicantsController : Controller
    {
        private projectV2Context db = new projectV2Context();

        // GET: Applicants
        public ActionResult Index(string search)
        {
            var applicants = db.Applicants.Where(a => a.SSN.Length != 0);

            if (!String.IsNullOrEmpty(search))
            {
                applicants = applicants.Where(a => a.LastName.Contains(search) ||
                a.SSN.Contains(search));
                ViewBag.Search = search;
            }

            return View(applicants.ToList());
        }

        // GET: Applicants/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Applicant applicant = db.Applicants.Find(id);
            if (applicant == null)
            {
                return HttpNotFound();
            }
            return View(applicant);
        }

        // GET: Applicants/Create
        public ActionResult Create()
        {
            List<SelectListItem> States = new List<SelectListItem>();
            States.Add(new SelectListItem { Text = "Alabama", Value = "Alabama" });
            States.Add(new SelectListItem { Text = "Alaska", Value = "Alaska" });
            States.Add(new SelectListItem { Text = "Arizona", Value = "Arizona" });
            States.Add(new SelectListItem { Text = "Arkansas", Value = "Arkansas" });
            States.Add(new SelectListItem { Text = "California", Value = "California" });
            States.Add(new SelectListItem { Text = "Colorado", Value = "Colorado" });
            States.Add(new SelectListItem { Text = "Connecticut", Value = "Connecticut" });
            States.Add(new SelectListItem { Text = "Delaware", Value = "Delaware" });
            States.Add(new SelectListItem { Text = "Florida", Value = "Florida" });
            States.Add(new SelectListItem { Text = "Georgia", Value = "Georgia" });
            States.Add(new SelectListItem { Text = "Hawaii", Value = "Hawaii" });
            States.Add(new SelectListItem { Text = "Idaho", Value = "Idaho" });
            States.Add(new SelectListItem { Text = "Illinois", Value = "Illinois" });
            States.Add(new SelectListItem { Text = "Indiana", Value = "Indiana" });
            States.Add(new SelectListItem { Text = "Iowa", Value = "Iowa" });
            States.Add(new SelectListItem { Text = "Kansas", Value = "Kansas" });
            States.Add(new SelectListItem { Text = "Kentucky", Value = "Kentucky" });
            States.Add(new SelectListItem { Text = "Louisiana", Value = "Louisiana" });
            States.Add(new SelectListItem { Text = "Maine", Value = "Maine" });
            States.Add(new SelectListItem { Text = "Maryland", Value = "Maryland" });
            States.Add(new SelectListItem { Text = "Massachusetts", Value = "Massachusetts" });
            States.Add(new SelectListItem { Text = "Michigan", Value = "Michigan" });
            States.Add(new SelectListItem { Text = "Minnesota", Value = "Minnesota" });
            States.Add(new SelectListItem { Text = "Mississippi", Value = "Mississippi" });
            States.Add(new SelectListItem { Text = "Missouri", Value = "Missouri" });
            States.Add(new SelectListItem { Text = "Montana", Value = "Montana" });
            States.Add(new SelectListItem { Text = "Nebraska", Value = "Nebraska" });
            States.Add(new SelectListItem { Text = "Nevada", Value = "Nevada" });
            States.Add(new SelectListItem { Text = "New Hampshire", Value = "New Hampshire" });
            States.Add(new SelectListItem { Text = "New Jersey", Value = "New Jersey" });
            States.Add(new SelectListItem { Text = "New Mexico", Value = "New Mexico" });
            States.Add(new SelectListItem { Text = "New York", Value = "New York" });
            States.Add(new SelectListItem { Text = "North Carolina", Value = "North Carolina" });
            States.Add(new SelectListItem { Text = "North Dakota", Value = "North Dakota" });
            States.Add(new SelectListItem { Text = "Ohio", Value = "Ohio" });
            States.Add(new SelectListItem { Text = "Oklahoma", Value = "Oklahoma" });
            States.Add(new SelectListItem { Text = "Oregon", Value = "Oregon" });
            States.Add(new SelectListItem { Text = "Pennsylvania", Value = "Pennsylvania" });
            States.Add(new SelectListItem { Text = "Rhode Island", Value = "Rhode Island" });
            States.Add(new SelectListItem { Text = "South Carolina", Value = "South Carolina" });
            States.Add(new SelectListItem { Text = "South Dakota", Value = "South Dakota" });
            States.Add(new SelectListItem { Text = "Tennessee", Value = "Tennessee" });
            States.Add(new SelectListItem { Text = "Texas", Value = "Texas" });
            States.Add(new SelectListItem { Text = "Utah", Value = "Utah" });
            States.Add(new SelectListItem { Text = "Vermont", Value = "Vermont" });
            States.Add(new SelectListItem { Text = "Virginia", Value = "Virginia" });
            States.Add(new SelectListItem { Text = "Washington", Value = "Washington" });
            States.Add(new SelectListItem { Text = "West Virginia", Value = "West Virginia" });
            States.Add(new SelectListItem { Text = "Wisconsin", Value = "Wisconsin" });
            States.Add(new SelectListItem { Text = "Wyoming", Value = "Wyoming" });
            ViewBag.Majors = States;

            List<SelectListItem> Majors = new List<SelectListItem>();
            Majors.Add(new SelectListItem { Text = "Math", Value = "Math" });
            Majors.Add(new SelectListItem { Text = "Information Technology", Value = "Information Technology" });
            Majors.Add(new SelectListItem { Text = "Computer Science", Value = "Computer Science" });
            Majors.Add(new SelectListItem { Text = "Biology", Value = "Biology" });
            Majors.Add(new SelectListItem { Text = "Chemistry", Value = "Chemistry" });
            Majors.Add(new SelectListItem { Text = "Engineering", Value = "Engineering" });
            ViewBag.Majors = Majors;

            List<SelectListItem> EnrollmentSemester = new List<SelectListItem>();
            EnrollmentSemester.Add(new SelectListItem { Text = "Spring", Value = "Spring" });
            EnrollmentSemester.Add(new SelectListItem { Text = "Summer", Value = "Summer" });
            EnrollmentSemester.Add(new SelectListItem { Text = "Fall", Value = "Fall" });
            ViewBag.EnrollmentSemester = EnrollmentSemester;


            return View();
        }


        // POST: Applicants/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,MiddleName,LastName,SSN,EmailAddress,HomePhone,CellPhone,Street,City,State,Zipcode,DOB,Gender,HSName,HSCity,GraduationDate,GPA,MathScore,VerbalScore,Major,EnrollmentSemester,EnrollmentYear,SubmissionDate")] Applicant applicant)
        {
            if (ModelState.IsValid)
            {
                Applicant matchingApplicant = db.Applicants.Where(cm => string.Compare(cm.SSN, applicant.SSN, true) == 0).FirstOrDefault();

                if (applicant == null)
                {
                    return HttpNotFound();
                }

                if (matchingApplicant != null)
                {
                    ModelState.AddModelError("SSN", "An applicant with this SSN already exist. Each applicant can apply only once.");
                    return View(applicant);
                }

                if (applicant.MathScore + applicant.VerbalScore < 1000)
                {
                    ModelState.AddModelError("VerbalScore", "You are not qualified. The total of Math Score and Verbal Score must be greater than 1000");
                    return View(applicant);
                }

                db.Applicants.Add(applicant);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(applicant);
        }

        // GET: Applicants/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Applicant applicant = db.Applicants.Find(id);
            if (applicant == null)
            {
                return HttpNotFound();
            }

            List<SelectListItem> States = new List<SelectListItem>();
            States.Add(new SelectListItem { Text = "Alabama", Value = "Alabama" });
            States.Add(new SelectListItem { Text = "Alaska", Value = "Alaska" });
            States.Add(new SelectListItem { Text = "Arizona", Value = "Arizona" });
            States.Add(new SelectListItem { Text = "Arkansas", Value = "Arkansas" });
            States.Add(new SelectListItem { Text = "California", Value = "California" });
            States.Add(new SelectListItem { Text = "Colorado", Value = "Colorado" });
            States.Add(new SelectListItem { Text = "Connecticut", Value = "Connecticut" });
            States.Add(new SelectListItem { Text = "Delaware", Value = "Delaware" });
            States.Add(new SelectListItem { Text = "Florida", Value = "Florida" });
            States.Add(new SelectListItem { Text = "Georgia", Value = "Georgia" });
            States.Add(new SelectListItem { Text = "Hawaii", Value = "Hawaii" });

projectV2/Views/Applicants/Create.cshtml
@model GMUAdmissionPortal.Models.Applicant

@{
    ViewBag.Title = "Apply";
}

<h2>Apply</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MiddleName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SSN, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SSN, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SSN, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HomePhone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HomePhone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HomePhone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CellPhone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CellPhone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CellPhone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select class="form-control" id="State" name="State">
                <option value="">Select State</option>
                <option value="Alabama">Alabama</option>
                <option value="Alaska">Alaska</option>
                <option value="Arizona">Arizona</option>
                <option value="Arkansas">Arkansas</option>
                <option value="California">California</option>
                <option value="Colorado">Colorado</option>
                <option value="Connecticut">Connecticut</option>
                <option value="Delaware">Delaware</option>
                <option value="Florida">Florida</option>
                <option value="Georgia">Georgia</option>
                <option value="Hawaii">Hawaii</option>
                <option value="Idaho">Idaho</option>
                <option value="Illinois">Illinois</option>
                <option value="Indiana">Indiana</option>
                <option value="Iowa">Iowa</option>
                <option value="Kansas">Kansas</option>
                <option value="Kentucky">Kentucky</option>
                <option value="Louisiana">Louisiana</option>
                <option value="Maine">Maine</option>
                <option value="Maryland">Maryland</option>
                <option value="Massachusetts">Massachusetts</option>
                <option value="Michigan">Michigan</option>
                <option value="Minnesota">Minnesota</option>
                <option value="Mississippi">Mississippi</option>
                <option value="Missouri">Missouri</option>
                <option value="Montana">Montana</option>
                <option value="Nebraska">Nebraska</option>
                <option value="Nevada">Nevada</option>
                <option value="New Hampshire">New Hampshire</option>
                <option value="New Jersey">New Jersey</option>
                <option value="New Mexico">New Mexico</option>
                <option value="New York">New York</option>
                <option value="North Carolina">North Carolina</option>
                <option value="North Dakota">North Dakota</option>
                <option value="Ohio">Ohio</option>
                <option value="Oklahoma">Oklahoma</option>
                <option value="Oregon">Oregon</option>
                <option value="Pennsylvania">Pennsylvania</option>
                <option value="Rhode Island">Rhode Island</option>
                <option value="South Carolina">South Carolina</option>
                <option value="South Dakota">South Dakota</option>
                <option value="Tennessee">Tennessee</option>
                <option value="Texas">Texas</option>
                <option value="Utah">Utah</option>
                <option value="Vermont">Vermont</option>
                <option value="Virginia">Virginia</option>
                <option value="Washington">Washington</option>
                <option value="West Virginia">West Virginia</option>
                <option value="Wisconsin">Wisconsin</option>
                <option value="Wyoming">Wyoming</option>

            </select>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Zipcode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Zipcode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Zipcode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "date-picker" } })
            @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="col-md-10">
                @Html.RadioButton("Gender", "Male") Male <br />
                @Html.RadioButton("Gender", "Female") Female
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HSName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HSName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HSName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HSCity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HSCity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HSCity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GraduationDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GraduationDate, new { htmlAttributes = new { @class = "date-picker" } })
            @Html.ValidationMessageFor(model => model.GraduationDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GPA, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GPA, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GPA, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MathScore, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MathScore, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MathScore, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.VerbalScore, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.VerbalScore, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.VerbalScore, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Major, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select class="form-control" id="Major" name="Major">
                <option value="">Select Major</option>
                <option value="Math">Math</option>
                <option value="Information Technology">Information Technology</option>
                <option value="Computer Science">Computer Science</option>
                <option value="Biology">Biology</option>
                <option value="Chemistry">Chemistry</option>
                <option value="Engineering">Engineering</option>
            </select>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EnrollmentSemester, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select class="form-control" id="EnrollmentSemester" name="EnrollmentSemester">
                <option value="">Select Enrollment Semester</option>
                <option value="Spring">Spring</option>
                <option value="Summer">Summer</option>
                <option value="Fall">Fall</option>
            </select>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EnrollmentYear, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EnrollmentYear, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EnrollmentYear, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.HiddenFor(model => model.SubmissionDate, htmlAttributes: new { @Value = @DateTime.Now.ToString("MM-dd-yyyy") })
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    $(function () {
        // This will make every element with the class "date-picker" into a DatePicker element
        $('.date-picker').datepicker();
    })
</script>

projectV2/Views/Applicants/Index.cshtml
@model IEnumerable<GMUAdmissionPortal.Models.Applicant>

@{
    ViewBag.Title = "Applicant List";
}

<h2>Applicant List</h2>

@using (Html.BeginForm("Index", "Applicants", FormMethod.Get))
{
    @Html.TextBox("Search", null, new { @class = "search-box", @placeholder = "Search by Last Name or SSN" })
    <input class="search" type="submit" value="Search" />
    <input type="hidden" name="Search" id="Search" value="@ViewBag.Search" />
}



<table class="table">
    <tr>
        <th>
            Student Name
        </th>
        <th>
            Submission Date
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GPA)
        </th>
        <th>
            Combined SAT Score
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EnrollmentSemester)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EnrollmentYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AdmissionDecision)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
                @Html.DisplayFor(modelItem => item.MiddleName)
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubmissionDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GPA)
            </td>
            <td>
                @Html.Raw(item.MathScore + item.VerbalScore)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EnrollmentSemester)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EnrollmentYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AdmissionDecision)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>